#!/bin/sh
set -e

VERSION=0.0.3
RELEASE=0

PWD=`pwd`
WORK=/tmp/less_shitty_rpmbuild_$$

go build -o remirror .

rpmbuild --quiet --buildroot /tmp/$WORK \
	-D "_version   $VERSION" \
	-D "_release   $RELEASE" \
	-D "_origin    $PWD" \
	-D "_sourcedir $WORK/source" \
	-D "_rpmdir    $WORK/rpm"       \
	-D "_builddir  $WORK/build"   \
	-bb remirror.spec

cp $WORK/rpm/*/*.rpm $PWD
rm -rf $WORK

